### ISSUE TITLE
TypeError: Cannot read property 'errors' of undefined

### ISSUE THREAD

**Issue by Vanuan** [hmalphettes/elasticsearch-streams#16]
There's something wrong with error handling.
```
  var bulkExec = function(bulkCmds, callback) {
    elasticClient.bulk({
      index : 'my-index',
      type  : 'my-type',
      body  : bulkCmds
    }, callback);
  };
  var ws = new WritableBulk(bulkExec);
  var toBulk = new TransformToBulk(function getIndexTypeId(doc) { return { _id: doc.id }; });
  stream.pipe(toBulk).pipe(ws);
```

```
/src/node_modules/elasticsearch-streams/lib/writable-bulk.js:80
     if (resp.errors && resp.items) {
             ^
 
 TypeError: Cannot read property 'errors' of undefined
     at /src/node_modules/elasticsearch-streams/lib/writable-bulk.js:80:13
     at respond (/src/node_modules/elasticsearch/src/lib/transport.js:308:9)
     at /src/node_modules/elasticsearch/src/lib/transport.js:336:7
     at null.<anonymous> (/src/node_modules/elasticsearch/src/lib/transport.js:365:7)
     at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by hmalphettes** [comment]
Thanks @Vanuan .
